## INTERMEDIATE PYTHON


In [1]:
x=[1,2,3]
x_iter=iter(x)

In [4]:
print(next(x_iter))     ## 

3


In [1]:
class yrange:
# n is the number upto which i want the range
    def __init__(self,n):
        self.i=0
        self.n=n
#iterable and iterator function that makes class iterable
    def __iter__(self):
        return self
    def __next__(self):
        if self.i<self.n:
            i=self.i
            self.i+=1
            return i
        else:
            raise StopIteration()

In [2]:
for x in yrange(5):
    print(x)

0
1
2
3
4


In [5]:
import numpy as np
a=np.array([[1,2,3,4,5]])
print(a)
print(type(a))
print(a.shape)

[[1 2 3 4 5]]
<class 'numpy.ndarray'>
(1, 5)


In [8]:
b=np.array([[1],[2],[3]])
print(b)    #np.ones(r,c),np.ones(r,c),np.full((r,c),element) "IDENTITY MAXTRIX"np.eye(4)
randomMatrix=np.random.random((2,5))
print(randomMatrix)

[[1]
 [2]
 [3]]
[[0.46772143 0.33609826 0.79023436 0.17469095 0.27733369]
 [0.35709976 0.20773929 0.67657378 0.90788477 0.99762384]]
