In [2]:
import numpy as np

### linear Algebra

In [3]:
x=np.array([2,3,4,5])
print(x.shape)
print(x)
print(type(x))
x1=np.array([[1],[2],[3],[4]])
print(x1.shape)
print(x1)
print(type(x1))
x1=x1.reshape(-1,2)
print(x1)

(4,)
[2 3 4 5]
<class 'numpy.ndarray'>
(4, 1)
[[1]
 [2]
 [3]
 [4]]
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]


## TENSORS:matrices with more than 2 axes


In [12]:
x2=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]])
print(x2.shape)  #2 rows 3 colums 3 depth
print(x2)          

(2, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]


In [15]:
print(x1)
xo=np.transpose(x1)
print(xo)
xy=np.transpose(x2)
print(xy)


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[[ 1 11]
  [ 4 14]
  [ 7 17]]

 [[ 2 12]
  [ 5 15]
  [ 8 18]]

 [[ 3 13]
  [ 6 16]
  [ 9 19]]]


## Broadcasting

In [22]:
l=[1,3,5,7]
l=np.array(l)
print(l**2)
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(np.sqrt(c))

[ 1  9 25 49]
[[1 2 3]
 [4 5 6]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [34]:
lpinf=np.linalg.norm(l,ord=np.inf)
print(lpinf)
lp=np.linalg.norm(xy)
print(lp)


7.0
48.68264577855234
