In [24]:
import numpy as np
np.random.seed(1)
a=np.random.rand(2,3)
print(a)
a=np.random.randn(2,3)
print(a)
a=np.random.randint(2,10,3)
print(a)

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]]
[[-0.52817175 -1.07296862  0.86540763]
 [-2.3015387   1.74481176 -0.7612069 ]]
[5 6 4]


In [25]:
np.random.seed(2)
a=np.random.rand(2,3)
print(a)

[[0.4359949  0.02592623 0.54966248]
 [0.43532239 0.4203678  0.33033482]]


In [32]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(np.max(a,axis=0))
print(np.min(a,axis=1))
print(np.mean(a))
print(np.median(a[0]))
k=np.array([1,2,3,4])
w=np.array([1,2,3,4])
print(np.average(k,weights=w))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[7 8 9]
[1 4 7]
5.0
2.0
3.0


In [35]:
u=np.mean(k)
myStd=np.sqrt(np.mean(abs(k-u)**2))
print(myStd)
d=np.std(k)
print(d)

1.118033988749895
1.118033988749895


In [37]:
v=(d**2)
print(v)

1.2500000000000002
